version: '3'

services:
  days:
    build:
      context: .
      dockerfile: days.Dockerfile
    ports:
      - "${HTTP_PORT_DAYS}:${HTTP_PORT_DAYS}"
    volumes:
      - ./src/days:/app/src
  # postgres:
  #   image: postgres:9.6
  #   restart: always
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  #     POSTGRES_USER: "${POSTGRES_USER}"
  #     POSTGRES_DB: "${POSTGRES_DB}"
  #   volumes:
  #     - './data/postgres:/var/lib/postgresql/data'
  # mongo:
  #   image: mongo:3.4
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - './data/mongo:/data/db'